apiVersion: v1
kind: ConfigMap
metadata:
  name: l4-responder-config
  labels:
    app: l4-responder
data:
  config.yaml: |
    app: l4-responder
    hosts:
      poli-worker-00:
        ranges:
          - from: 10
            to: 200
          - from: 250
            to: 300
