FROM python:3.10-slim

# Install gcc and iptables dev dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    iptables \
    libnfnetlink-dev \
    libnetfilter-conntrack-dev \
    && apt-get clean

# Set work directory
WORKDIR /app

# Copy files

COPY responder.py .
RUN  pip install --upgrade pip
# Install Python dependencies
RUN pip install netifaces

# Entry point
CMD ["python", "responder.py"]
